export default [
  // {value: "AL", label: "Albania"},
  // {value: "AD", label: "Andorra"},
  // {value: "AT", label: "Austria"},
  // {value: "BY", label: "Belarus"},
  { value: 'BE', label: 'Belgium' },
  // {value: "BA", label: "Bosnia and Herzegovina"},
  // {value: "BG", label: "Bulgaria"},
  // {value: "HR", label: "Croatia"},
  // {value: "CY", label: "Cyprus"},
  // {value: "CZ", label: "Czech Republic"},
  // {value: "DK", label: "Denmark"},
  // {value: "EE", label: "Estonia"},
  // {value: "FI", label: "Finland"},
  // {value: "FR", label: "France"},
  // {value: "DE", label: "Germany"},
  // {value: "GR", label: "Greece"},
  // {value: "HU", label: "Hungary"},
  // {value: "IS", label: "Iceland"},
  // {value: "IE", label: "Ireland"},
  // {value: "IT", label: "Italy"},
  // {value: "LV", label: "Latvia"},
  // {value: "LI", label: "Liechtenstein"},
  // {value: "LT", label: "Lithuania"},
  { value: 'LU', label: 'Luxemburg' },
  // {value: "MK", label: "North Macedonia"},
  // {value: "MT", label: "Malta"},
  // {value: "MD", label: "Moldova"},
  // {value: "MC", label: "Monaco"},
  // {value: "ME", label: "Montenegro"},
  { value: 'NL', label: 'Netherlands' },
  // {value: "NO", label: "Norway"},
  // {value: "PL", label: "Poland"},
  // {value: "PT", label: "Portugal"},
  { value: 'RO', label: 'Romania' },
  // {value: "RU", label: "Russia"},
  // {value: "SM", label: "San Marino"},
  // {value: "RS", label: "Serbia"},
  // {value: "SK", label: "Slovakia"},
  // {value: "SI", label: "Slovenia"},
  { value: 'ES', label: 'Spain' },
  // {value: "SE", label: "Sweden"},
  // {value: "CH", label: "Switzerland"},
  // {value: "UA", label: "Ukraine"},
  { value: 'UK', label: 'United Kingdom' },
  // {value: "VA", label: "Vatican City"}
];
